### PR TITLE
Use-Manage Form

### PR DESCRIPTION
**Pull request by ColinMcNeil**
# Release Notes

Give forms and inputs UCONN design.

# Screenshot

## Basic text inputs
screen shot 2018-12-04 at 10 27 58 am

## Select Dropdown
screen shot 2018-12-04 at 10 28 31 am

## Control Groups
screen shot 2018-12-04 at 10 43 09 am

## Order Form
screen shot 2018-12-04 at 10 43 15 am

### CODE REVIEW

**Comment by jhanggi** [comment]
Also, I wonder if it might be worth doing some restructuring of the CSS files and split them out into a `app/form.scss` and a `app/use_manage.scss`? I'd also be ok, if we do a bigger refactoring of everything once we get a little further and see what the diff between this branch and `master`

**Comment by ColinMcNeil** [comment]
The left padding issue is not appearing for me. I did a fixup/rebase after submitting the PR that fixed it for me. Maybe you didn't have it? I improved the contrast and spacing in the select dropdown. I agree a refactor of all of these changes would be good because nucore.css is getting quite bloated, but Dan wants this released ASAP.

**Comment by jhanggi** [comment]
I'm still seeing the padding issue on Chrome and Safari. It doesn't seem to be as much of a problem in Firefox, though it maybe could use a little more. This is only in non-chosen `select`s.

**Comment by ColinMcNeil** [comment]
Interesting because the text transform is just CSS. I guess that's just how capybara works. The merge conflicts should be resolved and the selects should have padding.

**Comment by jhanggi** [comment]
Looks like more conflicts since I just merged the button PR 😃 

I just pushed up #1795 which should work in either upcase or regular mode. I'll merge that in to master and then get `uconn-design-updates` up to date.

**Comment by ColinMcNeil** [comment]
Okay, all set on the rebase.

**Pull request merged**
