### PR TITLE
[#133346] Include boilerplate and user-entered content when logging bulk email content

### PR DESCRIPTION
**Pull request by drench**
This changes bulk email logging so that it includes the unalterable "canned" parts of the subject and body along with user-entered text.

As a side-effect it ended up simplifying `BulkEmail::Mailer` quite a bit.

### CODE REVIEW

**Comment by jhanggi** [comment]
Not sure where it's happening, but now, the greeting it not getting interpolated; it's sending the email as "Hello Firstname Lastname,"

**Comment by drench** [comment]
> the greeting it not getting interpolated

Good catch; I think I found it. The injected `BulkEmail::ContentGenerator` takes a `recipient` but this isn't setting it, so it's falling back to the default `#recipient_name`.

**Comment by drench** [comment]
Updated

**Comment by jhanggi** [comment]
If I send via instrument offline, the "Hello" is present in both the emails and the log, but the canned "Example Instrument has been taken offline. You may receive additional messages regarding the status of this instrument." is not.

**Comment by drench** [comment]
Give it another test. I didn't bisect to be sure, but I think this loss of the `product_id` parameter (which is the root of the message change) happened earlier.

**Comment by jhanggi** [comment]
👍

**Pull request merged**
