### PR TITLE
[#137103] bundle update awesome-nested-set gem

### PR DESCRIPTION
**Pull request by meara**
https://pm.tablexi.com/issues/137103

### CODE REVIEW

**Comment by jhanggi** [comment]
Maybe the removal of the monkey patch would be good to include here?

**Comment by meara** [comment]
@jhanggi monkey patch?

**Comment by jhanggi** [comment]
What waggles did in https://github.com/tablexi/nucore-dartmouth/pull/126

**Comment by meara** [comment]
Yep, will remove that in #1186 I think.

**Pull request merged**
