### PR TITLE
Split facility sub-items to their own columns

### PR DESCRIPTION
**Pull request by ColinMcNeil**
# Release Notes

Instead of a single list of objects belonging to a facility, multiple columns representing each type of object are used.

# Screenshot

## Before
image

## After
image

### CODE REVIEW

**Comment by ColinMcNeil** [comment]
## Release Notes
We have placed this feature into its own feature-flag.

## Mobile Screenshot
image

As you can see, the columns wrap responsively.

**Comment by ColinMcNeil** [comment]
This PR is in a state where we think is is ready to be merged with your requested changes and checks.

**Comment by vandrijevik** [comment]
Hi @ColinMcNeil, @jhanggi is on vacation for a couple of weeks, so I just wanted to let you know that this is on our radar, but since he’s been involved with the review so far, it may be a little while before Jason gets back to you!

**Comment by jhanggi** [comment]
I did a little stylistic cleanup on the CSS (use two spaces and add a space between the class name and the `{`, but otherwise is good. I'll merge this as soon as it passes CI.

**Pull request merged**
