### PR TITLE
[#137398] temp feature flag timed services

### PR DESCRIPTION
**Pull request by meara**
Feature flag for timed services while feature is being worked on.

### CODE REVIEW

**Comment by meara** [comment]
I think we'll probably want to remove this feature flag once the feature is complete--it's a little awkward code-wise, and there's a few spots it doesn't cover if a timed service already exists. For example, if a timed service has been added as an accessory on an instrument, it will still be shown as addable to a reservation.

For a temporary flag, while no timed services exist in stage/prod, I think this is fine, but we wouldn't want to leave this lying around once the feature is complete.

**Comment by jhanggi** [comment]
I agree this should go away once we're ready with the feature. In the meantime, this feels like it's touching a few more places than it really needs to assuming that there aren't existing TimedServices. For example, the facility show view should not show a section if there are no products of that type. And many of the scopes shouldn't do anything different if there aren't any TimedServices.

I would expect the only place we really need to flag is the sidebar for the Products tab in order to prevent creating a TimedService (I don't care too much if the route is protected or not). What's the reason we need to touch these other sections?

**Comment by meara** [comment]
I think I effectively decided in the middle that it wasn't practical to comprehensively flag everything--if we're comfortable with this being more of a temporary, "let's prevent people from accidentally interacting with this feature before it's ready" than a true comprehensive feature flag, I think that makes sense. I'll scale back what this PR is doing accordingly.

**Comment by jhanggi** [comment]
Yeah, I think the prevent people from using it before it's ready is the way to think about this feature flag. I'm fine making it available for everyone once it's ready.

**Comment by meara** [comment]
@jhanggi good to merge on this then?

**Pull request merged**
