### PR TITLE
[#133776] offline reservations display on calendar/timeline

### PR DESCRIPTION
**Pull request by meara**
- https://pm.tablexi.com/issues/133776

- Show the offline blocks on the facility timeline view (I feel like this could be pretty useful). If we do this we should make sure auto-canceled reservations are in front of the offline block
- Show the offline blocks in the calendar on the place reservation view. Show when ordering on behalf of.
- Show the offline blocks in the calendar where you take the instrument online and offline

screen shot 2017-07-12 at 5 31 29 pm

screen shot 2017-07-12 at 5 45 50 pm

screen shot 2017-07-12 at 5 46 22 pm

### CODE REVIEW

**Comment by meara** [comment]
I still need to do some testing around how things display when there are auto-canceled reservations. However, does this otherwise look okay? Currently the offline reservations appear basically identically to regular admin reservations--are we okay with that behavior?

**Comment by meara** [comment]
With conflicting reservations over instrument downtime:

screen shot 2017-07-13 at 1 03 28 pm
screen shot 2017-07-13 at 1 03 48 pm
screen shot 2017-07-13 at 1 04 04 pm

**Comment by jhanggi** [comment]
This looks pretty ok. I'd like it if we could differentiate between admin reservations and offline reservations, at least in text. Can you do that on the timeline view? The JS calendar might be dependent on the work I'm doing for adding user information, though this might be something you could make the `title` dynamic in CalendarPresenter, even if the JS doesn't use it yet.

**Comment by meara** [comment]
screen shot 2017-07-13 at 3 46 53 pm
screen shot 2017-07-13 at 3 51 11 pm

**Comment by jhanggi** [comment]
That looks good. Hopefully these questions are just confirming it works: what does it look like when the offline reservation spans day boundaries? Also, what do you see for an ongoing offline incident? If the answer is nothing, I think that's probably fine for now.

**Comment by meara** [comment]
For currently down instruments, nothing shows up on the calendar--there is unchanged existing behavior that displays warning messages, etc.

screen shot 2017-07-14 at 12 48 38 pm
screen shot 2017-07-14 at 12 47 46 pm
screen shot 2017-07-14 at 12 48 19 pm

**Comment by meara** [comment]
Offline reservations spanning days display reasonably as well:

screen shot 2017-07-14 at 12 57 40 pm
screen shot 2017-07-14 at 12 57 54 pm
screen shot 2017-07-14 at 12 57 19 pm

**Pull request merged**
