### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by mlineen**

### CODE REVIEW

**Comment by mlineen** [comment]
@jhanggi your wish is my comand

**Comment by drench** [comment]
We're going to need something like this while we're still on Rails 3.2:

```
Rails/ActionFilter:
  EnforcedStyle: filter # TODO: remove after upgrading to Rails 4
```

I don't know if it belongs in `.rubocop_todo.yml` or `.rubocop-txi.yml`

**Comment by jhanggi** [comment]
Looks like Rails/FindEach needs to be undone. It converts `.all.each` to `all.find_each`,  which doesn't work in 3.2 because `all` in 3.2 executes the SQL and turns it into an array.

**Comment by jhanggi** [comment]
@mlineen I think we're at a more stable point in open/master where we can run this and hopefully get it in quickly. Watch out for Rails/ActionFilter and Rails/FindEach as they caused problems the last time. Probably best to just start a new branch and close this one. 

And we should make sure that github and codeclimate are set up to run rubocop on PRs.

**Pull request closed without merging**
