### PR TITLE
[#160883] Configurable iat offset for SciShield

### PR DESCRIPTION
**Pull request by giladshanan**
# Release Notes

Running into an issue with ~1 min lag between server time and API time.

### CODE REVIEW

**Review by jossim — APPROVED** [review]

**Comment by jossim** [comment]
On infrastructure, should we add sync'ing with a NTP server?

Seems like servers should have pretty accurate time

**Comment by giladshanan** [comment]
@jossim Good question - I jumped on the server and it turns out the RTC was 1 minute behind UTC for some reason.
I ran `hwclock --systohc` to "set the hardware clock from the current system time" and things are synced up now.

**Comment by jossim** [comment]
@giladshanan interesting. It may still drift over time. Not sure if this is Ubuntu or not, but it's pretty easy to setup Ubuntu to sync with atomic clocks

https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-20-04

**Comment by giladshanan** [comment]
@jossim it looks like the sync is enabled for the `corum` user but not for `root`.  I'm going to close this for now since we have a way forward.

**Pull request closed without merging**
